apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: geek-festa-sample
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geek-festa-sample
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
