apiVersion: v1
kind: Service
metadata:
  name: geek-festa-sample
  labels:
    app: geek-festa-sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: geek-festa-sample
  type: LoadBalancer